import room2 from "../assets/room2.jpg";
import room1 from "../assets/room1.jpg";
import room3 from "../assets/room3.jpg";
import room4 from "../assets/room4.jpg";
import uuid from "react-uuid";

export const roomsList = [
  {
    title: "Queen Bed A-12324",
    images: [room1],
    room_type: "Single Bed",
    room_number: 10,
    amenities: [
      { a_name: "wifi", icon: "wifi", isChecked: true },
      { a_name: "air_conditioner", icon: "air_conditioner" },
      { a_name: "double_bed", icon: "double_bed" },
      { a_name: "towels", icon: "towels", isChecked: true },
      { a_name: "shop_near", icon: "shop_near" },
      { a_name: "cleaning", icon: "cleaning" },
      { a_name: "breakfast", icon: "breakfast" },
      { a_name: "kitchen", icon: "kitchen" },
      { a_name: "shower", icon: "shower" },
    ],
    price: 245,
    discount: 10,
    offer: "yes",
    offer_price: 145,
    description: "Beautiful and cozy room ",
    cancellation:
      "Any cancellation or reschedule made less than 10 days will result in a cancellation fee. The amount of the fee will be equal to 20% of the reserved services or $100, whichever is more.",
    status: "Avaliable",
  },
  {
    title: "Classic Double Bed B-12324",
    images: [room2],
    room_type: "Double Bed",
    room_number: 3,
    amenities: [
      { a_name: "wifi", icon: "wifi", isChecked: true },
      { a_name: "air_conditioner", icon: "air_conditioner" },
      { a_name: "double_bed", icon: "double_bed" },
      { a_name: "towels", icon: "towels" },
      { a_name: "shop_near", icon: "shop_near" },
      { a_name: "cleaning", icon: "cleaning" },
      { a_name: "breakfast", icon: "breakfast" },
      { a_name: "kitchen", icon: "kitchen" },
      { a_name: "shower", icon: "shower" },
    ],
    price: 345,
    discount: 10,
    offer: "yes",
    offer_price: 245,
    description: "Beautiful and cozy room ",
    cancellation:
      "Any cancellation or reschedule made less than 10 days will result in a cancellation fee. The amount of the fee will be equal to 20% of the reserved services or $100, whichever is more.",
    status: "Booked",
  },
  {
    title: "Luxury Room  D-1231",
    images: [room3],
    room_type: "Double Superior",
    room_number: 2,
    amenities: [
      { a_name: "wifi", icon: "wifi", isChecked: true },
      { a_name: "air_conditioner", icon: "air_conditioner" },
      { a_name: "double_bed", icon: "double_bed" },
      { a_name: "towels", icon: "towels" },
      { a_name: "shop_near", icon: "shop_near" },
      { a_name: "cleaning", icon: "cleaning" },
      { a_name: "breakfast", icon: "breakfast" },
      { a_name: "kitchen", icon: "kitchen" },
      { a_name: "shower", icon: "shower" },
    ],
    price: 345,
    discount: 10,
    offer: "yes",
    offer_price: 300,
    description: "Beautiful and cozy room ",
    cancellation:
      "Any cancellation or reschedule made less than 10 days will result in a cancellation fee. The amount of the fee will be equal to 20% of the reserved services or $100, whichever is more.",
    status: "Avaliable",
  },
  {
    title: "Luxury Suite Room  X-1342",
    images: [room4],
    room_type: "Suite",
    room_number: 5,
    amenities: [
      { a_name: "wifi", icon: "wifi", isChecked: true },
      { a_name: "air_conditioner", icon: "air_conditioner" },
      { a_name: "double_bed", icon: "double_bed" },
      { a_name: "towels", icon: "towels" },
      { a_name: "shop_near", icon: "shop_near" },
      { a_name: "cleaning", icon: "cleaning" },
      { a_name: "breakfast", icon: "breakfast" },
      { a_name: "kitchen", icon: "kitchen" },
      { a_name: "shower", icon: "shower" },
    ],
    price: 345,
    discount: 10,
    offer: "yes",
    offer_price: 300,
    description: "Beautiful and cozy room ",
    cancellation:
      "Any cancellation or reschedule made less than 10 days will result in a cancellation fee. The amount of the fee will be equal to 20% of the reserved services or $100, whichever is more.",
    status: "Avaliable",
  },
  {
    title: "Queen Bed A-12324",
    images: [room1],
    room_type: "Single Bed",
    room_number: 10,
    amenities: [
      { a_name: "wifi", icon: "wifi", isChecked: true },
      { a_name: "air_conditioner", icon: "air_conditioner" },
      { a_name: "double_bed", icon: "double_bed" },
      { a_name: "towels", icon: "towels" },
      { a_name: "shop_near", icon: "shop_near" },
      { a_name: "cleaning", icon: "cleaning" },
      { a_name: "breakfast", icon: "breakfast" },
      { a_name: "kitchen", icon: "kitchen" },
      { a_name: "shower", icon: "shower" },
    ],
    price: 245,
    offer: "yes",
    offer_price: 145,
    cancellation:
      "Any cancellation or reschedule made less than 10 days will result in a cancellation fee. The amount of the fee will be equal to 20% of the reserved services or $100, whichever is more.",
    status: "Booked",
    description: "Beautiful and Cozy Room",
  },
];
